### ISSUE TITLE
能否针对你写的框架写一个使用说明？

### ISSUE THREAD

**Issue by laoyuan1992** [dgflash/oops-framework#1]
目前看你的框架有点懵，主要是你集合太多东西在里面啦，对新手不是很好，所以是否考虑有空写几篇使用文档？这样或许使用的人会更多

**Comment by dgflash** [comment]
教程我后续有空会写一下，现在框架里我写了一套代码教程，里面的业务逻辑很简单，主要是让阅读者理解设计思想。你可以先看这个DEMO，有问题在交流群中发问题发出来。




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "dgflash/oops-framework"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sun, Apr 10, 2022 03:41 PM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[dgflash/oops-framework] 能否针对你写的框架写一个使用说明？ (Issue #1)





 
目前看你的框架有点懵，主要是你集合太多东西在里面啦，对新手不是很好，所以是否考虑有空写几篇使用文档？这样或许使用的人会更多

**Comment by laoyuan1992** [comment]
你集合太多东西在里面啦，其实感觉很乱。可以把框架简化一下，搞最刚需的一些内容就可以啦

**Comment by dgflash** [comment]
你现在的问题是看到东西多，有些内容不一定要用，而我是做大型游戏的，里面每个技术都是我用过的，提供出来相当于帮你已经测试了一遍。你只希望获取到你想用的东西。这个很难实现，就算是cocos那么多技术库，你也不可能所有东西用，因为我要适应的是一个面，而不是一个点。你感觉用不到的内容可以不用管它，或者把它删掉并不影响开发。


框架本身是一个底偶合的技术库。每个技术都可以独立拆分。所以你说的乱不存在。


我里面提供了一个小游戏demo。演示了一套业务框架的思想。这个是用于项目的核心。由于我无法用语言跟你们讲。所以理解起来会要你多思考一下。或在群里交流。


后续我有空我会整理一些教程，你要是急着用就在群里交流，我会回复的。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月12日(周二) 凌晨0:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dgflash/oops-framework] 能否针对你写的框架写一个使用说明？ (Issue #1)




 
你集合太多东西在里面啦，其实感觉很乱。可以把框架简化一下，搞最刚需的一些内容就可以啦
