### ISSUE TITLE
某些平台，如番茄小说小游戏会报错，集中在外部导入插件上，seedrandom，crypto-es

### ISSUE THREAD

**Issue by TippingGame** [dgflash/oops-framework#10]
USER_RUNTIME_ERROR
loadScript error: src/assets/miniprogram_npm/crypto.jsError: src/assets/miniprogram_npm/crypto.js load failed
USER_RUNTIME_ERROR
loadScript error: src/assets/libs/miniprogram_npm/crypto.jsError: src/assets/libs/miniprogram_npm/crypto.js load failed
USER_RUNTIME_ERROR
loadScript error: src/miniprogram_npm/crypto/index.jsError: src/miniprogram_npm/crypto/index.js load failed
USER_RUNTIME_ERROR
loadScript error: src/assets/libs/seedrandom/crypto/index.jsError: src/assets/libs/seedrandom/crypto/index.js load failed
USER_RUNTIME_ERROR
loadScript error: src/assets/libs/seedrandom/miniprogram_npm/crypto.jsError: src/assets/libs/seedrandom/miniprogram_npm/crypto.js load failed

**Comment by TippingGame** [comment]
<anonymous> in Array.find at line 0:0
at src/assets/libs/seedrandom/seedrandom.min.218e6.js in ? at line 1:1568
at src/assets/libs/seedrandom/seedrandom.min.218e6.js in ? at line 1:1678
cocos-js/cc.1062b.js in ? at line 2:800255

**Comment by dgflash** [comment]
这二个都是第三方库，你可以考虑手动删除这两个库，并不是必备功能。不会影响你的游戏逻辑



------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2024年9月14日(星期六) 晚上6:01
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: [dgflash/oops-framework] 某些平台，如番茄小说小游戏会报错，集中在外部导入插件上，seedrandom，crypto-es (Issue #10)














 
USER_RUNTIME_ERROR
 loadScript error: src/assets/miniprogram_npm/crypto.jsError: src/assets/miniprogram_npm/crypto.js load failed
 USER_RUNTIME_ERROR
 loadScript error: src/assets/libs/miniprogram_npm/crypto.jsError: src/assets/libs/miniprogram_npm/crypto.js load failed
 USER_RUNTIME_ERROR
 loadScript error: src/miniprogram_npm/crypto/index.jsError: src/miniprogram_npm/crypto/index.js load failed
 USER_RUNTIME_ERROR
 loadScript error: src/assets/libs/seedrandom/crypto/index.jsError: src/assets/libs/seedrandom/crypto/index.js load failed
 USER_RUNTIME_ERROR
 loadScript error: src/assets/libs/seedrandom/miniprogram_npm/crypto.jsError: src/assets/libs/seedrandom/miniprogram_npm/crypto.js load failed
