### ISSUE TITLE
optimize ResLoader.release logic

### ISSUE THREAD

**Issue by zjw552048** [dgflash/oops-framework#4]
cocos资源管理模块在 v2.4 做了升级，在释放资源时，开发者只需要关注资源本身，引擎会 自动释放 其依赖资源，不再需要通过 getDependsRecursively 手动获取依赖。
测试截图
![image](https://user-images.githubusercontent.com/21374439/224876176-65a5ac0f-8086-4b21-86b6-8afb731c5aec.png)
![image](https://user-images.githubusercontent.com/21374439/224876201-8cd91353-4e68-4d3e-a0af-a9c11f131c15.png)
![image](https://user-images.githubusercontent.com/21374439/224876208-e225d99e-8250-470e-9d7a-5bf894cdf4ec.png)

**Comment by zjw552048** [comment]
仓库弄错了

**Comment by dgflash** [comment]
感谢分享，代码已更新。
